"""
Django settings for khullasikshya_project project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import json
import os

with open('config.json', 'r') as f:
    config = json.load(f)
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#rab(6_=#)a8w*(-1$0n=n+pk7j4v^@c*jy1^lbs2+glsz2va8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # For Local Apps
    'home',
    'login_signup',
    'admin_home',
    'blog',
    'programming',
    'notice',
    'contact',
    'note',
    'about',
    'ckeditor',
    'ckeditor_uploader',

    # Designing Part
    'sweetify',
    'crispy_forms',
    'bootstrap_modal_forms',

    # For Social Media site login app
    'django.contrib.sites',
    # Apps required for allauth(social media login)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Providers
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'khullasikshya_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'khullasikshya_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config['DEFAULT']['DATABASE_NAME'],
        'USER': config['DEFAULT']['DATABASE_USER'],
        'PASSWORD': config['DEFAULT']['DATABASE_PASS'],
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {'charset': 'utf8mb4'},
        'init_command': 'SET foreign_key_checks = 0;',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    # Static Files haru ko direcotry dekhako... i.e hamile static folder banako xau.. so tyo folder ko naam 'static' xa ... yo static folder ma sabbai static files haru xa
    os.path.join(BASE_DIR, 'static')
]
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom Django auth settings

AUTH_USER_MODEL = 'login_signup.User'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# For Connecting Bootstrap alerts to Django message tags. This messages comes from viwes.py and we show this alert message in templates
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# SMTP Configuration                                          # yo tala ko chai Password Reset mail send garna ko lagi chaine kura haru ho

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # yo line ma j xa tei nai lekna parxa
EMAIL_HOST = config['DEFAULT']['EMAIL_HOST']  # gmail ko id vayera gmail.com gareko
EMAIL_PORT = config['DEFAULT']['EMAIL_PORT']  # Since we are using TLS, so we use EMAIL_PORT = 587
EMAIL_USE_TLS = True  # TLS lai TRUE garne
EMAIL_HOST_USER = config['DEFAULT']['EMAIL_HOST_USER']  # jun gmail batw reset email pathaune ho tyo email ID lekhinxa
EMAIL_HOST_PASSWORD = config['DEFAULT']['EMAIL_HOST_PASSWORD']

# For Social Media Login (Gmail & Facebook)
SITE_ID = 3

LOGIN_URL = 'login'  # This one is used when we use decorators like @login_required in views.py. This gives the path to redirect to login page if user isn't login
LOGIN_REDIRECT_URL = "home"
SWEETIFY_SWEETALERT_LIBRARY = 'sweetalert2'
CKEDITOR_UPLOAD_PATH = "media/ck_uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'width': 'auto',
        'toolbar': 'full',
        'toolbar_Full': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'], ['Source'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['NumberedList', 'BulletedList'],
            ['Indent', 'Outdent'],
            ['Maximize'],
        ],
        'extraPlugins': 'justify,liststyle,indent, codesnippet',

    },

}
